'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LTACheckingWithoutbudget

    '''<summary>
    '''radScriptBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radScriptBlock As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''lbl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ChecknewHire1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChecknewHire1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblChecknewHire1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChecknewHire1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlChecknewHire1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChecknewHire1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnChecknewHire1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChecknewHire1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ChecknewHire2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChecknewHire2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblChecknewHire2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChecknewHire2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlChecknewHire2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChecknewHire2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnChecknewHire2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChecknewHire2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ChecknewHire3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChecknewHire3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblChecknewHire3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChecknewHire3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlChecknewHire3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChecknewHire3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnChecknewHire3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChecknewHire3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''radWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radWindow As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''btnOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOk As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHide As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''radWindow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radWindow1 As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''btnOk1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOk1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnHide1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHide1 As Global.System.Web.UI.WebControls.Button
End Class
