'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReimbursementOthers

    '''<summary>
    '''radScriptBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radScriptBlock As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''windowmanager2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents windowmanager2 As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtReimbursementType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReimbursementType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNote As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBalance As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntryDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''radDatepickerEntryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radDatepickerEntryDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''linkPolicySection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkPolicySection As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lstReimburseType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstReimburseType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panelDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelDates As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblTransactionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTransactionDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDateFieldRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateFieldRequired As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''radDatePickerTransactionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radDatePickerTransactionDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''validTransactionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validTransactionDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblExtraDateField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtraDateField As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReqExtraDateField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReqExtraDateField As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''radDatepickerExtraDateField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radDatepickerExtraDateField As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''validExtraDateField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validExtraDateField As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblExtraField7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtraField7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReq7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReq7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''radExtraField7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radExtraField7 As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''validEF7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validEF7 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblExtraField8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtraField8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReq8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReq8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''radExtraField8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radExtraField8 As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''validEF8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validEF8 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''panelDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelDetail As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblExtraField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtraField1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReq1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReq1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExtraField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtraField1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validEF1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validEF1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''NumbervalidEF1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NumbervalidEF1 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''TextvalidEF1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextvalidEF1 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''AllEF1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AllEF1 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''lblExtraField2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtraField2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReq2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReq2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExtraField2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtraField2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validEF2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validEF2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''NumbervalidEF2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NumbervalidEF2 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''TextvalidEF2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextvalidEF2 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''AllEF2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AllEF2 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''lblExtraField3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtraField3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReq3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReq3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExtraField3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtraField3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validEF3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validEF3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''NumbervalidEF3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NumbervalidEF3 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''TextvalidEF3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextvalidEF3 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''AllEF3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AllEF3 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''lblExtraField5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtraField5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReq5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReq5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExtraField5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtraField5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validEF5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validEF5 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''NumbervalidEF5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NumbervalidEF5 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''TextvalidEF5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextvalidEF5 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''AllEF5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AllEF5 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''lblExtraField11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtraField11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReq11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReq11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExtraField11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtraField11 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''validEF11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validEF11 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblExtraField4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtraField4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReq4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReq4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExtraField4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtraField4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''validEF4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validEF4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblExtraField6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtraField6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReq6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReq6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExtraField6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtraField6 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''validEF6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validEF6 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''trextrafield control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trextrafield As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblExtraField9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtraField9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReq9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReq9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExtraField9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtraField9 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''validEF9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validEF9 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblExtraField10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtraField10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReq10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReq10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExtraField10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtraField10 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''validEF10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validEF10 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblTransactionDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTransactionDetail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTransactionDetailMandatory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTransactionDetailMandatory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TransactionDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionDetail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validDetail As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''NumbervalidEF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NumbervalidEF As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''TextvalidEF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextvalidEF As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''panelTotalBill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelTotalBill As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblTotalBillField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalBillField As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTotalBillField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalBillField As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validBillAmount0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validBillAmount0 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''NumbervalidBillAoumnt0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NumbervalidBillAoumnt0 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''lblAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Amount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validBillAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validBillAmount As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''NumbervalidBillAoumnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NumbervalidBillAoumnt As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''lnkMultiple control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkMultiple As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''radGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radGrid1 As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''panelCSVUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelCSVUpload As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linkCSVTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkCSVTemplate As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblFileUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFileUpload As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''radAsynUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radAsynUpload As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''btnUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''trguidelines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trguidelines As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''panelBillupload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelBillupload As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbluploadheader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbluploadheader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RadAsyncUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAsyncUpload1 As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''btnUploadBill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUploadBill As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''trupload2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trupload2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RadAsyncUpload2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAsyncUpload2 As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''truploadbtn2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents truploadbtn2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''btnUploadBill2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUploadBill2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Literal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lit1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''chkDisclaimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDisclaimer As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblsave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsave As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hidmaxlen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidmaxlen As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidwebtableid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidwebtableid As Global.System.Web.UI.WebControls.HiddenField
End Class
